// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow.Api.Data;

#nullable disable

namespace TaskFlow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814072713_AddJobApplicationCompany")]
    partial class AddJobApplicationCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TaskFlow.Api.Models.AgentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AgentLogs");
                });

            modelBuilder.Entity("TaskFlow.Api.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestionSessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestionSessionId", "OwnerId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("TaskFlow.Api.Models.ResumeContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestionSessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestionSessionId", "OwnerId")
                        .IsUnique();

                    b.ToTable("ResumeContexts");
                });

            modelBuilder.Entity("TaskFlow.Api.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSection")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TailoredContent")
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("AssignedToId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compose a three-line haiku (5-7-5 syllables) about the fall season.",
                            Kind = "Generic",
                            Priority = "Low",
                            Status = "Todo",
                            Title = "Write a haiku about autumn",
                            UpdatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Give three short, creative uses for a paperclip.",
                            Kind = "Generic",
                            Priority = "Low",
                            Status = "Todo",
                            Title = "List three uses for a paperclip",
                            UpdatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suggest one name for a friendly helper robot, with a one-line reason.",
                            Kind = "Generic",
                            Priority = "Low",
                            Status = "Todo",
                            Title = "Name a friendly robot",
                            UpdatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Write a single clear sentence explaining what a to-do app does.",
                            Kind = "Generic",
                            Priority = "Low",
                            Status = "Todo",
                            Title = "Describe a to-do app in one sentence",
                            UpdatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Provide one interesting fact about the number seven.",
                            Kind = "Generic",
                            Priority = "Low",
                            Status = "Todo",
                            Title = "Share a fun fact about the number 7",
                            UpdatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TaskFlow.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andrew@taskflow.dev",
                            Name = "Andrew Van Delden",
                            PasswordHash = "placeholder"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@taskflow.dev",
                            Name = "Demo User",
                            PasswordHash = "placeholder"
                        });
                });

            modelBuilder.Entity("TaskFlow.Api.Models.TaskItem", b =>
                {
                    b.HasOne("TaskFlow.Api.Models.JobApplication", "Application")
                        .WithMany("Tasks")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskFlow.Api.Models.User", "AssignedTo")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Application");

                    b.Navigation("AssignedTo");
                });

            modelBuilder.Entity("TaskFlow.Api.Models.JobApplication", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskFlow.Api.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
